# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TokyoRubyKaigi11
email: tokyorubykaigi11@atdot.net
description: > # this means to ignore newlines until "baseurl:"
  Website of TokyoRubyKaigi11.
baseurl: "/tokyo11" # the subpath of your site, e.g. /blog
url: "http://regional.rubykaigi.org/tokyo11" # the base hostname & protocol for your site
twitter_username: tokyork11
github_username:  ko1

# Build settings
markdown: kramdown

languages:
  - code: en
    name: English
    path: en
  - code: ja
    name: 日本語
    path: ''
    default: true
